### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by jakejgordon** [RallyCommunity/super-customizable-cfd#1]
I get the below error when trying to run npm install. Was able to get the task to run by manually installing the latest version of grunt-webdriver-jasmine-runner via "npm install grunt-webdriver-jasmine-runner --save-dev". I also get the bottom error when trying to run tests.

![npm_install_issue](https://cloud.githubusercontent.com/assets/3045786/3629451/be74c900-0ea0-11e4-9f46-be4e87f4ac5b.jpg)

![error_running_tests](https://cloud.githubusercontent.com/assets/3045786/3629517/88d7294a-0ea1-11e4-8543-a1c94526d542.jpg)

**Comment by krmorse** [comment]
npm install seems to work fine for me.
