### ISSUE TITLE
Keep Getting: "Your request requires access to a workspace or project for which you do not have permission. Contact your subscription administrator to request permission." most of the time

### ISSUE THREAD

**Issue by sps786** [RallyCommunity/super-customizable-cfd#10]
Want to thank you for writing this app! this does what I exactly need.

The problem I have been having is, I keep getting this error: 
Your request requires access to a workspace or project for which you do not have permission. Contact your subscription administrator to request permission.

most of the time, 3/10 tries work and I can see the area graph.

I am a workspace admin. So there shouldn't be any permission issues.

**Comment by sps786** [comment]
I have paste the code in custom html app in Rally

**Comment by sps786** [comment]
Would appreciate any help on this! I am kinda stuck deploying this.

**Comment by krmorse** [comment]
This is a known defect with charts based on the Lookback API.  Hopefully it should be resolved soon...

**Comment by krmorse** [comment]
Actually, you can probably help us debug the issue.  The error you are getting is a generic error for the service returning a non-200 error code.  Could you take a look in your network tab for the request generated while the chart is loading to see what the response looks like?  Are there errors?

**Comment by sps786** [comment]
Thank you for your response! 
Sorry was tied up with sprint plan yesterday so couldn't get back earlier.

In the network tab I see:
![image](https://cloud.githubusercontent.com/assets/6841766/6485556/980b02fa-c252-11e4-9919-0a335d40ee33.png)

In the response tab, I see "Failed to load response data"

**Comment by krmorse** [comment]
Interesting.  That would appear that the request is timing out on the client side.  I'll try to dig into this a little deeper and see if I can provide you a workaround...

**Comment by krmorse** [comment]
You should be able to insert this override right before the first Ext.define in your app to work around the issue:

Ext.define('Rally.data.lookback.SnapshotRestProxyOverride', {
    override: 'Rally.data.lookback.SnapshotRestProxy', 
    timeout: 300000
});

That should set the timeout to be 5 minutes which should be more than enough.

**Comment by sps786** [comment]
Thanks a bunch!
I see that the response time varied 2.7 mins to 4.8 mins, In my scripts I will increase time out a tad to be on safe side.

Appreciate your help on this!

**Comment by sps786** [comment]
Is Max Timeout 5 mins?
I still get few instances of timeout..

**Comment by sps786** [comment]
Now the error i get is:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/analytics/v2.0/service/rally/workspace/XXXXXXX/artifact/snapshot/query.js">GET&nbsp;/analytics/v2.0/service/rally/workspace/XXXXXXX/artifact/snapshot/query.js</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>
</body></html>

**Comment by krmorse** [comment]
There isn't a max timeout, so if you need to bump it up to something higher than 5 minutes that should be fine...  As far as the proxy error I'm honestly not sure what might be going on there... that doesn't sound like an issue with the app itself.

**Comment by sps786** [comment]
Yes agree, must be some other issue.
I will debug our environment.

Thanks for your reply!
