### ISSUE TITLE
Plotting  and displaying incorrect Values on the graph

### ISSUE THREAD

**Issue by arunka1984** [RallyCommunity/super-customizable-cfd#11]
I could see that the graph is plotting on wrong values.How can we get the values used to plot the graph.Also one more question here is when we have a release we have the start and end date of a release,why we need to get it from settings

Your help on this would be much appreciated.

Thanks
Arun

**Comment by krmorse** [comment]
You can now export the data from this app to a csv file so you can inspect it.  The app also now respects timebox scoped custom pages and you can configure it to automatically use the timebox start/end dates in the settings.

Closing as fixed in v1.1.0
