### ISSUE TITLE
Only one X-axis label showing

### ISSUE THREAD

**Issue by dgonz782** [RallyCommunity/super-customizable-cfd#19]
First, thank you for this app!  I'm running into a issue where only one date is displaying.  Screenshot provided.  
![image](https://user-images.githubusercontent.com/35971470/35584354-c2187652-05c2-11e8-9f84-f67768409d0f.png)

**Comment by krmorse** [comment]
Hmm, weird.  If you hover over any of the data points all the way to the right of the graph the endpoint should be correct, yes?  I bet we probably just need to change the granularity of the x-axis.  Seems like it should always end with a tick label too.

**Comment by dgonz782** [comment]
Yes, the last data point shows the date as 2018-01-26.

**Comment by krmorse** [comment]
Fixed in v1.1.2

**Comment by dgonz782** [comment]
Thank you!!!
