### ISSUE TITLE
Instructions for how to copy/paste the app

### ISSUE THREAD

**Issue by jakejgordon** [RallyCommunity/super-customizable-cfd#9]
Hi John, for the average user, they are just going to want to come here and find => copy => paste the HTML for the app into a custom HTML widget in Rally. Maybe you could put a 1-liner at the top of the readme to tell people to go to /deploy/App.txt and copy/paste those contents. This way you won't lose anyone who is super lazy (as most people are). Thanks again and I'm looking forward to checking out the updated version!

**Comment by krmorse** [comment]
This app has been incorporated into the in-product community app catalog and as such, there should no longer be a need to manually copy/paste html.

If there is still a usecase for that though, here is a guide for working with rally app builder and deploying html: https://help.rallydev.com/apps/2.1/doc/#!/guide/app_builder
